library(tidyverse)
library(lubridate)
library(readr)
library(ggplot2)
library(ggmap)
library(dplyr)
library(grid)
library(geosphere)
ext_tracks_widths <- c(7, 10, 2, 2, 3, 5, 5, 6, 4, 5, 4, 4, 5, 3, 4, 3, 3, 3,
                       4, 3, 3, 3, 4, 3, 3, 3, 2, 6, 1)
ext_tracks_colnames <- c("storm_id", "storm_name", "month", "day",
                         "hour", "year", "latitude", "longitude",
                         "max_wind", "min_pressure", "rad_max_wind",
                         "eye_diameter", "pressure_1", "pressure_2",
                         paste("radius_34", c("ne", "se", "sw", "nw"), sep = "_"),
                         paste("radius_50", c("ne", "se", "sw", "nw"), sep = "_"),
                         paste("radius_64", c("ne", "se", "sw", "nw"), sep = "_"),
                         "storm_type", "distance_to_land", "final")

ext_tracks <- read_fwf("ebtrk_atlc_1988_2015.txt", 
                       fwf_widths(ext_tracks_widths, ext_tracks_colnames),
                       na = "-99")

a<-ext_tracks %>% mutate(storm_id=paste(storm_name,year,sep='_'),date=ymd_h(paste(year,month,day,hour)), longitude=longitude*-1) %>% 
  select(-c('month','day','year','hour','storm_name','rad_max_wind', 'eye_diameter', 'pressure_1', 'pressure_2','storm_type', 'distance_to_land', 'final' ))
b<-a %>% pivot_longer(
  cols = radius_34_ne:radius_64_nw,
  names_to = c("wind_speed",'direction'),
  names_pattern = "radius_(.*)_(.*)")
storm_data<-b %>% pivot_wider(names_from=direction, values_from = value)


#' Compute the points representing the storm polygon
#' 
#' Take a set of coordinates and radii and return the polygon coordinates
#'
#' @param x0 X longitude of the storm's center
#' @param y0 Y latitude of the storm's center
#' @param ne Radius of the north-east quadrant
#' @param se Radius of the south-east quadrant
#' @param sw Radius of the south-west quadrant
#' @param nw Radius of the north-west quadrant
#' @param scale_radii Scale of the polygon, default to 1
#' @return A data.frame containing columns `lat` and `lon` for each point in the polygon
calculate_poly<-function(x,y,r_ne,r_se,r_sw,r_nw,wind_speed, scale_radii=1){
  r_ne<-r_ne*1852*scale_radii
  r_se<-r_se*1852*scale_radii
  r_nw<-r_nw*1852*scale_radii
  r_sw<-r_sw*1852*scale_radii
  coords<-c(x,y)
  circle1<-geosphere::destPoint(coords,b=1:90,d=r_ne)
  circle2<-geosphere::destPoint(coords,b=91:180,d=r_se)
  circle3<-geosphere::destPoint(coords,b=181:270,d=r_sw)
  circle4<-geosphere::destPoint(coords,b=271:360,d=r_nw)
  totalshape<-rbind(circle1,circle2,circle3,circle4)
  totdf<-data.frame(totalshape)
  totdf
  
}

#' Draw a panel with a polygon from the storm data
#'
#' @param data data.frame with storm information
#' @param panel_scales object used by GGPLOT2 / GGMAP objects to scale data for plotting
#' @param coord the coordinate object with the transformations for plotting generated by GG methods
#' 
#' @return grob tree with polygon for plotting
draw_panel_function <- function(data, panel_scales, coord) {
  tree <- grid::gTree()
  for (i in 1:nrow(data)) {
    
    polypoints <- calculate_poly(x=data[i,]$x, y=data[i,]$y, r_ne=data[i,]$r_ne, r_nw=data[i,]$r_nw, r_se=data[i,]$r_se, r_sw=data[i,]$r_sw, scale_radii = data[1,]$scale_radii) %>%
      dplyr::rename(x = lon, y = lat) %>%
      coord$transform(panel_scales)
    grob <- grid::polygonGrob(x = polypoints$x, y = polypoints$y,gp = grid::gpar(col = data[i,]$colour, fill = data[i,]$fill, alpha = data[i,]$alpha))
    tree <- grid::addGrob(tree, grob)
  }
  tree
}

#' Construct a new class corresponding to the hurricane geom
#'
GeomHurricane <- ggplot2::ggproto("GeomHurricane", Geom,
                         required_aes = c('x','y','r_ne','r_se','r_nw','r_sw','wind_speed'),
                         default_aes = ggplot2::aes(color = "NA", fill = "NA", size = 0.5, linetype = 1, alpha = 0.8, scale_radii = 1),
                         draw_key = ggplot2::draw_key_polygon,
                         draw_panel = draw_panel_function
)


#' Add a layer to a GGMAP object with the 4-quadrant outline of a storm
#' 
#' @param mapping Set of aesthetic mappings created by aes() or aes_(). If specified and inherit.aes = TRUE (the default), it is combined with the default mapping at the top level of the plot. You must supply mapping if there is no plot mapping.
#' @param data The data to be displayed in this layer.
#' @param show.legend logical. Should this layer be included in the legends?
#' @param na.rm If FALSE, the default, missing values are removed with a warning. If TRUE, missing values are silently removed.
#' @param inherit.aes If FALSE, overrides the default aesthetics, rather than combining with them
#' 
#' @details  An alternative parameterisation is geom_polygon(), where each point defines a storm outline
#' @export
geom_hurricane <- function(mapping = NULL, data = NULL, stat = "identity", 
                           position = "identity", show.legend = NA, 
                           na.rm = FALSE, inherit.aes = TRUE, ...) {
  ggplot2::layer(
    data = data, 
    mapping = mapping,
    stat = stat,
    geom = GeomHurricane,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

ike<-storm_data %>%
  dplyr::filter( storm_id=='IKE_2008' & date==ymd_hms('2008-09-12 12:00:00') )

m<-get_map("Louisiana", zoom = 6, maptype = "toner-background") %>%
  ggmap(extent = "device") +
  geom_hurricane(data = ike,
                 aes(x = longitude, y = latitude,
                     r_ne = ne, r_se = se, r_nw = nw, r_sw = sw,wind_speed=wind_speed,
                     fill = wind_speed,
                     color = wind_speed)) +
  scale_color_manual(name = "Wind speed (kts)",
                     values = c("red", "orange", "yellow")) +
  scale_fill_manual(name = "Wind speed (kts)",
                    values = fills) + labs(title='Hurricane Ike 2008-09-12 12:00:00')

print(m)